"""Incremental ingest of LA City campaign contributions from Socrata into DuckDB.

The source has no change-data-capture to lean on, and the obvious watermarks are traps:

  * ``:updated_at`` and ``:created_at`` are identical for every row and move on every
    refresh. On 2026-08-30 every row read ``2026-08-30T13:38:40.211Z``; the next day
    every row read ``2026-08-31T15:59:06.514Z`` -- including a contribution dated 2003.
    They mark when the dataset was last rebuilt, not when a row changed.
  * ``:id`` is regenerated by the same rebuild, so it is not a stable surrogate key.

The publisher truncates and reloads. So we watermark on the business date instead, and
re-read a trailing window on every run because CA460 filings are amended after the fact.
Rows are merged on a content key rather than appended, which makes a re-read of an
amended period converge instead of duplicating.
"""

from __future__ import annotations

import hashlib
from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from typing import Any, Iterator

import dlt
import requests

DATASET_ID = "m6g2-gc6c"
RESOURCE_URL = f"https://data.lacity.org/resource/{DATASET_ID}.json"
VIEW_URL = f"https://data.lacity.org/api/views/{DATASET_ID}.json"

PAGE_SIZE = 50_000

# CA460 filings are amended after their period closes. A 120-day trailing re-read covers
# the semi-annual filing cadence plus the usual amendment lag; anything older is treated
# as settled. Widen this if the reconciliation test starts finding late movement.
AMENDMENT_LOOKBACK_DAYS = 120

# Dates before this are upstream data-entry errors (0121-03-08, 1409-08-01, 1973-05-31).
# They, and the 24 rows with no date at all, are pinned to the cursor floor so every run
# re-reads them. That is 32 rows -- a rounding error in bandwidth, and the alternative is
# a pipeline that quietly forgets they exist.
CURSOR_FLOOR = "1990-01-01"

# The columns that identify a contribution as disclosed. Deliberately every business
# column: the filer gives us nothing else to key on.
BUSINESS_COLUMNS = (
    "con_date", "con_name", "con_city_nm", "con_state_nm", "con_zip_cd",
    "con_occp", "con_empr", "cmt_nm", "cmt_id", "cmt_type", "cand_name",
    "seat_desc", "dist_num", "con_type", "con_desc", "con_amount",
    "con_amount_pd_forgiven", "form", "schedule", "per_beg_date", "per_end_date",
    "election_date", "election_desc", "int_name", "int_city_nm", "int_state_nm",
    "int_zip_cd", "int_occp", "int_empr", "memo",
)


def source_rebuilt_at() -> datetime:
    """When the publisher last rebuilt the dataset. Used to skip no-op runs."""
    meta = requests.get(VIEW_URL, timeout=60).json()
    return datetime.fromtimestamp(meta["rowsUpdatedAt"], tz=timezone.utc)


def cursor_date(row: dict[str, Any]) -> str:
    """A sanitised, always-parseable cursor value for a row.

    con_date cannot be the cursor directly. dlt parses the cursor field itself, so a
    single row dated 0121-03-08 raises "date value out of range" and aborts the whole
    extract regardless of the column type hint. Clamping implausible and missing dates
    to a floor keeps those rows in every pull instead of losing them.
    """
    raw = (row.get("con_date") or "")[:10]
    try:
        parsed = date.fromisoformat(raw)
    except ValueError:
        return CURSOR_FLOOR
    if parsed < date(1990, 1, 1) or parsed > date.today() + timedelta(days=365):
        return CURSOR_FLOOR
    return raw


def content_hash(row: dict[str, Any]) -> str:
    """Hash of the business columns as disclosed."""
    payload = "".join(str(row.get(c, "") or "") for c in BUSINESS_COLUMNS)
    return hashlib.blake2b(payload.encode("utf-8"), digest_size=16).hexdigest()


# Socrata types con_date as calendar_date, but letting the loader infer that produces a
# timestamp with a timezone, which shifts every date back seven hours and moves
# contributions across day -- and therefore reporting-period and election-cycle --
# boundaries. The raw layer stays faithful text; staging does the typing where it can be
# tested and where failures are visible.
RAW_TEXT_COLUMNS = {
    c: {"data_type": "text"}
    for c in (
        "con_date", "per_beg_date", "per_end_date", "election_date",
        "con_amount", "con_amount_pd_forgiven",
    )
}


@dlt.resource(
    name="contributions",
    write_disposition="merge",
    primary_key="_content_key",
    columns=RAW_TEXT_COLUMNS,
)
def contributions(
    contributed_after: dlt.sources.incremental[str] = dlt.sources.incremental(
        "_cursor_date",
        initial_value=CURSOR_FLOOR,
    ),
) -> Iterator[dict[str, Any]]:
    """Page through contributions on or after the watermark, oldest first."""
    watermark = contributed_after.last_value or CURSOR_FLOOR
    start = _apply_lookback(watermark)

    seen: dict[str, int] = defaultdict(int)
    ingested_at = datetime.now(tz=timezone.utc).isoformat()
    offset = 0
    while True:
        params = {
            # The trailing two predicates are not incidental. 24 rows have no
            # contribution date at all and 8 fall outside any plausible range; a bare
            # `>=` drops all 32 without comment. The first load did exactly that and
            # reported success.
            "$where": (
                f"(con_date >= '{start}' OR con_date IS NULL "
                f"OR con_date < '{CURSOR_FLOOR}')"
            ),
            "$order": "con_date,:id",
            "$limit": PAGE_SIZE,
            "$offset": offset,
        }
        page = requests.get(RESOURCE_URL, params=params, timeout=180).json()
        if not page:
            break

        for row in page:
            digest = content_hash(row)
            occurrence = seen[digest]
            seen[digest] += 1
            # Hashing the business columns alone is not enough. 1,395 rows here are
            # byte-identical to another row across all 30 columns, and they are not all
            # errors -- same-day instalments and the "and Affiliated Entities"
            # disclosure convention both produce legitimate twins. Merging on the hash
            # alone would silently delete $17.8M, so the occurrence index is part of
            # the key.
            row["_content_key"] = f"{digest}:{occurrence}"
            row["_cursor_date"] = cursor_date(row)
            row["_ingested_at"] = ingested_at
            yield row

        if len(page) < PAGE_SIZE:
            break
        offset += PAGE_SIZE


def _apply_lookback(watermark: str) -> str:
    """Rewind the watermark so amended filings are re-read rather than missed."""
    try:
        parsed = date.fromisoformat(watermark[:10])
    except ValueError:
        return CURSOR_FLOOR
    rewound = parsed - timedelta(days=AMENDMENT_LOOKBACK_DAYS)
    return max(rewound, date.fromisoformat(CURSOR_FLOOR)).isoformat()


@dlt.resource(name="load_snapshots", write_disposition="append")
def load_snapshots(rebuilt_at: datetime, row_count: int) -> Iterator[dict[str, Any]]:
    """One row per ingest, so successive rebuilds of the source can be diffed.

    Because the publisher truncates and reloads, an amendment is otherwise invisible --
    there is no version, no amendment flag, and no filing id. Retaining the shape of each
    load is what makes "what changed upstream?" answerable at all.
    """
    yield {
        "loaded_at": datetime.now(tz=timezone.utc).isoformat(),
        "source_rebuilt_at": rebuilt_at.isoformat(),
        "row_count": row_count,
        "lookback_days": AMENDMENT_LOOKBACK_DAYS,
    }


def source_row_count() -> int:
    response = requests.get(RESOURCE_URL, params={"$select": "count(1)"}, timeout=60)
    return int(response.json()[0]["count_1"])


def reconcile(warehouse_rows: int) -> None:
    """Fail loudly when the warehouse and the source disagree on row count.

    The first run of this pipeline loaded 418,716 of 418,748 rows and reported success.
    The 32 missing rows were 8 with dates outside any plausible range and 24 with no
    date at all, all silently excluded by the watermark predicate. A load that quietly
    drops rows is worse than one that fails, so this check is part of the pipeline
    rather than a test someone might not run.
    """
    source_rows = source_row_count()
    print(f"warehouse {warehouse_rows:,} | source {source_rows:,}")
    if warehouse_rows != source_rows:
        raise SystemExit(
            f"reconciliation failed: warehouse has {warehouse_rows:,} rows, "
            f"source reports {source_rows:,} (difference {source_rows - warehouse_rows:+,})"
        )
    print("reconciliation OK")


def main() -> None:
    pipeline = dlt.pipeline(
        pipeline_name="socrata_contributions",
        destination=dlt.destinations.duckdb("followthemoney.duckdb"),
        dataset_name="raw",
    )

    rebuilt_at = source_rebuilt_at()
    last_seen = pipeline.state.get("source_rebuilt_at")
    if last_seen == rebuilt_at.isoformat():
        print(f"source unchanged since {rebuilt_at.isoformat()}; nothing to do")
        return

    info = pipeline.run(contributions())
    print(info)

    with pipeline.sql_client() as client:
        with client.execute_query("select count(*) from contributions") as cursor:
            row_count = cursor.fetchone()[0]

    pipeline.run(load_snapshots(rebuilt_at, row_count))
    pipeline.state["source_rebuilt_at"] = rebuilt_at.isoformat()

    reconcile(row_count)


if __name__ == "__main__":
    main()
